### ISSUE TITLE
文章中如何插入图片

### ISSUE THREAD

**Issue by slayersbosh** [theme-kaze/hexo-theme-kaze#16]
MD中插入图片是本地绝对路径，如何展示出来呢？

**Comment by songhn233** [comment]
插入图片与主题无关，依赖 Hexo 行为。您可以在 `site/source` 下新建 `images` 或其他命名的文件夹并插入图片，在 Markdown 中通过 `![](/images/image.jpg)` 来插入图片。

同时也可以使用图床方案直接引用 url，更多细节参见 [Hexo 文档](https://hexo.io/zh-cn/docs/asset-folders)。

**Comment by songhn233** [comment]
如果没有其他问题将关闭这个issue。
