### ISSUE TITLE
反馈主题BUG

### ISSUE THREAD

**Issue by abbw** [theme-kaze/hexo-theme-kaze#17]
1. 文章页标题只显示网站名字
2. fslightbox无法使用，点击图片显示`invalid source`
3. 搜索和暗色模式图标应在最右边显示
4. 文章页，tag显示可以参考Sukka样式

**Comment by songhn233** [comment]
1.  文章在front matter中指定 `title` 即可在文章页显示标题，不明白只显示网站名是什么意思，请提供更具体的示例或站点。
2.  请首先参考该 [issue](https://github.com/theme-kaze/hexo-theme-kaze/issues/13)，可能是您的图源对跨域策略存在限制，主题 Fslightbox 本身应该是没有问题的，假如不是这些原因还是请您提供具体的示例或者站点供我们复现。
3.  这不属于一个 bug，搜索和暗色是否该偏移到最右这是每个主题设计上的理念不同，如果您有相关需求可以自行偏移。
4.  文章页的 tag 显示设计确实是一个问题，我现在的想法是提供配置项来让 tag 在页尾还是页首以及去除外边框。同时文章这些 meta 元素的布局也有重新排版的打算，如果您有其他建议可以继续在 issue 中反馈。

**Comment by abbw** [comment]
1. 文章front matter中已指定 `title`，但页面标题只会一直显示站点名字，而非显示文章的title
2图片确定是没问题的，能加载出来，不能点击放大显示。

示例：https://demo.qzkyl.ml/posts/17113.html

示例都可以重现以上2个问题(由于是临时站点，只有前4篇文章用于测试)

**Comment by songhn233** [comment]
1. 理解错了意思，浏览器显示的标题确实有问题，已在[devel 分支](https://github.com/theme-kaze/hexo-theme-kaze/commit/0f3e15b790e9e2f8b874ec5386e1770951400668)修复。
2.  感谢反馈，已[修复](https://github.com/theme-kaze/hexo-theme-kaze/commit/046b2ab4d49c06500e77f10238a45c287dcbe0ec)。

有关图片的问题假如方便的话可以直接存放在站点或者考虑一些其他的不对跨域限制的服务和 cdn 如 Jsdelivr 等来当作图床。假如一定需要原有的 gitee 来当作图床的话可能只能考虑 facybox 了，但是不建议为了一个功能引入 JQuery。

有其他问题和建议也欢迎反馈。

**Comment by abbw** [comment]
另外手机端上，部分地方如果是中文内容的话，位置会有少许偏移。

比如首页里的 `tag` 处，页脚的 `Copyright` 处

**Comment by abbw** [comment]
如果用了文章置顶，置顶的文章会排在第一页的最后面，其它主题不会

**Comment by songhn233** [comment]
手机存在的部分适配问题在该 [commit](https://github.com/theme-kaze/hexo-theme-kaze/commit/af42f4f63a0be46bfb20afdecda9dd8d1f588c78) 修复，这种情况似乎只有在安卓下的浏览器才会出现，目前修复了首页和文章页 `meta` 元素的偏移以及页脚的偏移，可能还有其他的偏移的问题。

文章置顶失效应该是由于主题在展示时又对文章按日期做了排序，应该已[修复](https://github.com/theme-kaze/hexo-theme-kaze/commit/e9420a69eb665d70c3eb12cc0f8eba9ad6dc2b94)，会考虑在 `v1.1.0` 版本集成置顶。

**Comment by abbw** [comment]
手机端搜索依然存在问题，滑到底部，搜索结果会出现在最顶部，而非跟随搜索框下方显示

另外fslightbox图源已改为Jsdelivr，但不知为何部分图片依然会显示 invalid source

还是推荐作者增加一种看图插件

**Comment by songhn233** [comment]
搜索没有仔细测试，已[修复](https://github.com/theme-kaze/hexo-theme-kaze/commit/dadfd9b7480685cbb112f364bfc4ef9a80991ddd)。

主题的看图插件确实存在问题。我们准备在 `v1.1.0` 后将 FslightBox 替换为 BaguetteBox，[已更新](https://github.com/theme-kaze/hexo-theme-kaze/commit/351b89bf290cadafc7f5ca0a8e510d8158a09663)。

插件效果可参考 [官方demo](https://feimosi.github.io/baguetteBox.js/)。同时产生了 `config.yml` 的字段修改：
```yaml
fslightbox:
  enable: true
```
修改为
```yaml
lightbox:
  enable: true
```

**Comment by abbw** [comment]
BaguetteBox如果首页有图片，也会加载样式，导致页面最底部有BaguetteBox的按钮图片

**Comment by songhn233** [comment]
> BaguetteBox如果首页有图片，也会加载样式，导致页面最底部有BaguetteBox的按钮图片

已[修复](https://github.com/theme-kaze/hexo-theme-kaze/commit/55c0dacd9dd5c61c4f417e6460a1727d650c2ff2)。

**Comment by Ch3nYe** [comment]
搜索功能不能使用
```  
search:
  enable: true
  path: search.json
  field: posts
  searchContent: true
```  
已经和默认配置相同了，还是开不起来搜索功能


>

**Comment by songhn233** [comment]
> 搜索功能不能使用
> 
> ```
> search:
>   enable: true
>   path: search.json
>   field: posts
>   searchContent: true
> ```
> 
> 已经和默认配置相同了，还是开不起来搜索功能
> 
> >

~~首先新问题建议新开个 issue~~


最好提供一个可以复现问题的 demo 仓库方便我们排查

当然也可以进行一下排查操作给我们定位

+ 确保当前采用的主题和 master 分支内容一致
+ 执行 `hexo clean, hexo g`
+ 确认生成后的 `public` 文件夹下有没有 `search.json`
+ 打开搜索框输入搜索内容后通过 `f12` 或其他方式打开浏览器调试工具查看报错

**Comment by Ch3nYe** [comment]
> > 搜索功能不能使用
> > ```
> > search:
> >   enable: true
> >   path: search.json
> >   field: posts
> >   searchContent: true
> > ```
> > 
> > 
> > 已经和默认配置相同了，还是开不起来搜索功能
> > >
> 
> ~首先新问题建议新开个 issue~
> 
> 最好提供一个可以复现问题的 demo 仓库方便我们排查
> 
> 当然也可以进行一下排查操作给我们定位
> 
> * 确保当前采用的主题和 master 分支内容一致
> * 执行 `hexo clean, hexo g`
> * 确认生成后的 `public` 文件夹下有没有 `search.json`
> * 打开搜索框输入搜索内容后通过 `f12` 或其他方式打开浏览器调试工具查看报错

你好，我先前出现的搜索功能开不起来的问题出现在Release: v1.0.5 这个版本中；
这个问题在最新的beta3-v1.1.0 已经解决了。希望大佬继续努力完善一些细节，再次感谢🙏

**Comment by Ch3nYe** [comment]
催更😁建议加入分析器 [https://statcounter.com/](https://statcounter.com/)

**Comment by songhn233** [comment]
> 催更😁建议加入分析器 https://statcounter.com/

statcounter 创建项目后就直接给了接入代码直接插进页面里就好了，主题似乎也没什么好集成的？

**Comment by Ch3nYe** [comment]
主题渲染公数学式换行符号\\总是被转义\\\\也不好使，辛苦看看能不能修一下
$$
det(J_G) =\frac{\partial{x_{d+1}}}{\partial{z_{d+1}}}\frac{\partial{x_{d+2}}}{\partial{z_{d+2}}}...\frac{\partial{x_D}}{\partial{z_D}} \\\\
=β_{d+1}β_{d+2}...β_{D}
$$

**Comment by songhn233** [comment]
> 主题渲染公数学式换行符号\总是被转义\\也不好使，辛苦看看能不能修一下
> $$
> det(J_G) =\frac{\partial{x_{d+1}}}{\partial{z_{d+1}}}\frac{\partial{x_{d+2}}}{\partial{z_{d+2}}}...\frac{\partial{x_D}}{\partial{z_D}} \\
> =β_{d+1}β_{d+2}...β_{D}
> $$

不好意思之前有点事所以 issue 一直没看

公式转译的问题是 Hexo 本身渲染机制问题，所以直接使用 mathjax 会出现一些符号无法使用的情况，这个可以参考[主题文档](https://demo.theme-kaze.top/latex/)，修改默认渲染器并使用 katex 应该就能解决这个问题了

我在文档的演示中也增加了你给的公式，可以看到能够正常换行
