### ISSUE TITLE
about 链接乱码

### ISSUE THREAD

**Issue by zzujay** [theme-kaze/hexo-theme-kaze#21]
将你的demo of hexo-theme-kaze的 about/index.md复制 到我的about文件下，启动后 只有这个index.md在中文下乱码，我尝试将index.md文件设置为UTF-8 和其他的中文编码 依然不行

我使用的是windows10

**Comment by zzujay** [comment]
![CMXAJXL )E6)NU~D3J@(I}0](https://user-images.githubusercontent.com/39424655/95651507-7af89280-0b1d-11eb-9e4b-c2f9c0783868.png)
![Uploading 56`A6U(UE`XMA8~4P`49J34.png…]()

**Comment by songhn233** [comment]
demo 都是 UTF-8，看你的截图好像没有乱码问题，请再描述的清楚一点

**Comment by zzujay** [comment]
![Uploading 56`A6U(UE`XMA8~4P`49J34.png…]()

**Comment by zzujay** [comment]
我按照文档 建立了about文件夹  在该文件夹下按照文档编写了index.md文件  然后启动服务，其他页面没有问题，但是点击about时，该页面出现第二张图所示的乱码

**Comment by zzujay** [comment]
![Uploading 乱码页面.png…]()

**Comment by zzujay** [comment]
![Uploading 乱码页面.jpg…]()

**Comment by songhn233** [comment]
请确认你的图片上传有没有问题，我们这里无法加载
![image](https://user-images.githubusercontent.com/47357585/95651800-47b70300-0b1f-11eb-9228-8e55b8319224.png)

确保 issue 的链接从 upload 转变为带 `githubusercontent.com` 的链接后在进行 comment，可以在 Preview 里进行确认

**Comment by zzujay** [comment]
![乱码页面](https://user-images.githubusercontent.com/39424655/95651865-a8ded680-0b1f-11eb-905e-6122fe6aef80.jpg)

**Comment by songhn233** [comment]
你的问题应该是 `source/about` 文件夹应该放在你的站点目录下而不是主题文件夹下，乱码应该是这个原因。

**Comment by zzujay** [comment]
ok 我尝试一下  感谢

**Comment by songhn233** [comment]
如果没有其他问题将关闭这个 issue。
