### ISSUE TITLE
分类/标签中有符号时会转义

### ISSUE THREAD

**Issue by onestravel** [theme-kaze/hexo-theme-kaze#27]
当分类/标签中有符号时，如 C++，再编译之后不会生成的 public 目录中对应分类/标签目录下未能生成 C++  目录，导致再网页上点击分类/标签 C++ 时，会出现404

**Comment by songhn233** [comment]
这是 Hexo 本身的问题，详见该 [issue](https://github.com/hexojs/hexo/issues/4104#issuecomment-607597936)，应该不被认为是一个 bug，所以可能需要在命名时避免特殊符号。

**Comment by onestravel** [comment]
这个我明白，hexo 会将部分特殊符号转为 - ，这个在html 显示时没有问题，只需要在路由链接的时候，找到对应 hexo 转义过的路由就可以，我对编写 hexo 主题的脚本不熟悉，没找到修改的地方，如果可以修改，尽量希望修改成点击后不出现404


下面是之前引用的另外一个主题中最终实现的效果

<a href="/categories/Android-NDK/C-C/" title="C/C++: 11">
                    <span class="chip center-align waves-effect waves-light
                             chip-default " style="background-color: #D5F5E3;">C/C++
                        <span class="tag-length">11</span>
                    </span>
                </a>

**Comment by onestravel** [comment]
`<a href="/categories/Android-NDK/C-C/" title="C/C++: 11">
                    <span class="chip center-align waves-effect waves-light
                             chip-default " style="background-color: #D5F5E3;">C/C++
                        <span class="tag-length">11</span>
                    </span>
                </a>`

**Comment by songhn233** [comment]
我刚刚提交了一个 [commit](https://github.com/theme-kaze/hexo-theme-kaze/commit/6ef342fb3d5dee1598aa143c959e9e57b62a6853)，这样应该能解决路由 404 的问题，你试一下？

**Comment by onestravel** [comment]
主菜单的不会404了，左侧边栏的分类/标签直接点击还是会出现404

**Comment by songhn233** [comment]
ok，已修复

**Comment by onestravel** [comment]
ok，我刚找到了 hexo 可以针对分类或标签，可以在 hexo 的配置文件中配置字典映射，这样修改后，就可以正常访问映射后的文件路由了，也可以解决转义的问题。
`
# Category & Tag
default_category: uncategorized
category_map:
  数据结构于算法: algorthm
  MySQL: mysql
  C++: cpp
tag_map:
`
