### ISSUE TITLE
搜索按钮无法显示，路径错误，不知道怎么搞

### ISSUE THREAD

**Issue by Uranus-s** [theme-kaze/hexo-theme-kaze#29]
报错：Refused to apply style from 'http://localhost:4000/at.alicdn.com/t/font_1952792_89b4ac4k4up.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
我新建了一个项目对比了一下，它这个路径不应该是localhost，但不知道怎么改，求解决

**Comment by songhn233** [comment]
正常来讲应该是没有问题的，可能是一些修改造成的影响

可以尝试一下找到主题文件夹 `hexo-theme-kaze/layout/_partial/head.ejs` 下 90-91 行处
```
<%- preload_css('//at.alicdn.com/t/font_1946621_i1kgafibvw.css') %>
<%- preload_css('//at.alicdn.com/t/font_1952792_89b4ac4k4up.css') %>
```
113-115 行处
```
<%- css('//at.alicdn.com/t/font_1946621_i1kgafibvw.css') %>
<%# social icon %>
<%- css('//at.alicdn.com/t/font_1952792_89b4ac4k4up.css') %>
```
修改为
```
<%- preload_css('https://at.alicdn.com/t/font_1946621_i1kgafibvw.css') %>
<%- preload_css('https://at.alicdn.com/t/font_1952792_89b4ac4k4up.css') %>
```
```
<%- css('https://at.alicdn.com/t/font_1946621_i1kgafibvw.css') %>
<%# social icon %>
<%- css('https://at.alicdn.com/t/font_1952792_89b4ac4k4up.css') %>
```
如果修改后依然无法解决最好提供我们可以复现问题的 demo 方便排查错误

**Comment by Uranus-s** [comment]
感谢 解决了 具体我也不知道怎么回事 我新建一个项目是完全没有问题的
