### ISSUE TITLE
about页面无法显示引用和列表

### ISSUE THREAD

**Issue by vbozhang** [theme-kaze/hexo-theme-kaze#30]
about页面内容是用一个index.md写的，但是markdown中引用和列表都无法显示，通过查询发现把\themes\kaze\source\css\_pages下的about.styl加上
ul{list-style-type: disc;}
就可以正常显示列表, 但是请问怎么能正常显示引用

**Comment by songhn233** [comment]
这是我们的失误 已在最新 `devel` 分支[修复](https://github.com/theme-kaze/hexo-theme-kaze/commit/45be886d935bb7c450a044d59231dbe0d2765fa7)

想要手动修复可以找到文件 `theme-kaze/layout/about.ejs` 中找到
```html
<div class="card card-content">
  <%- page.content %>
</div> 
```
修改为
```html
<div class="card card-content">
  <div class="post-content">
    <%- page.content %>
  </div>
</div> 
```
即可正常显示样式了
