### ISSUE TITLE
social_links无效

### ISSUE THREAD

**Issue by CCandle** [theme-kaze/hexo-theme-kaze#31]
~~我也不知道到底是bug还是我自己的配置问题~~
1.  ![image](https://user-images.githubusercontent.com/45314580/108062091-43ce5b00-7094-11eb-9a65-7c1ba7796d6d.png)
配置如图，social_links 是默认缩进的，但是在 [主题使用文档](https://demo.theme-kaze.top/document/#%E7%A4%BE%E4%BA%A4%E9%93%BE%E6%8E%A5) 中social_links 却没有缩进，这是第一个有点迷惑的地方
2. 配置好social_links 后，我却没有找到他到哪去了。。。
我印象中应该是在
![image](https://user-images.githubusercontent.com/45314580/108062434-bf300c80-7094-11eb-8d9e-7f235e5b8dbb.png)这个位置的，看到在about里面，就到about里面找，也没有发现。
请问该怎么解决？

**Comment by songhn233** [comment]
文档存在缩进错误的问题，现已修复。

无法显示图标是因为不合法的 icon 名称。demo 中的写法为
```yaml
social_links:
  - { icon: icon-github, link: https://github.com/theme-kaze/hexo-theme-Kaze }
```
icon 名称是在 iconfont 中的[对应编码](https://img.songhn.com/img/iconfont.png?imageslim)。

文档中有说明 icon 相关问题请参见[图标](https://demo.theme-kaze.top/document/#%E5%9B%BE%E6%A0%87)相关说明。一般情况下图标并不是以图片文件的形式使用，本主题通过 icon class 来显示图标，主题内置的所有社交图标已经在文档中进行展示。

假如有额外需要的图标可以在 [iconfont](https://www.iconfont.cn/) 中寻找并使用。简要流程如下：

查找合适的图标并加入购物车，之后点击购物车选择添加至项目，若之前无项目新建项目即可。之后查看当前项目，上方会有三个选项：Unicode、Font class、Symbol。选择 Font class 并生成在线代码并复制，之后找到主题文件 `hexo-theme-kaze/layout/_partial/head.ejs` 中 110 行左右的如下代码：
```js
  <%# main css %>
  <%- css('css/main.css') %>
  <%# default icon %>
  <%- css('//at.alicdn.com/t/font_1946621_i1kgafibvw.css') %>
  <%# social icon %>
  <%- css('//at.alicdn.com/t/font_1952792_89b4ac4k4up.css') %>
```
在 social icon 后一行添加自定义 icon 如
```js
<%- css('your generated links') %>
```
即可使用自定义图标。

如果有其他问题或者需求可以继续跟进 issue。

**Comment by Phenothalin** [comment]
肥肠感谢您的回复！问题已经解决！
原谅我是个小白😛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "theme-kaze/hexo-theme-kaze"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月16日(星期二) 晚上9:02
收件人:&nbsp;"theme-kaze/hexo-theme-kaze"<hexo-theme-kaze@noreply.github.com&gt;;
抄送:&nbsp;"CC&amp;le"<2987794676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [theme-kaze/hexo-theme-kaze] social_links无效 (#31)





 
文档存在缩进错误的问题，现已修复。
 
无法显示图标是因为不合法的 icon 名称。demo 中的写法为
 social_links:   - { icon: icon-github, link: https://github.com/theme-kaze/hexo-theme-Kaze }
 
icon 名称是在 iconfont 中的对应编码。
 
文档中有说明 icon 相关问题请参见图标相关说明。一般情况下图标并不是以图片文件的形式使用，本主题通过 icon class 来显示图标，主题内置的所有社交图标已经在文档中进行展示。
 
假如有额外需要的图标可以在 iconfont 中寻找并使用。简要流程如下：
 
查找合适的图标并加入购物车，之后点击购物车选择添加至项目，若之前无项目新建项目即可。之后查看当前项目，上方会有三个选项：Unicode、Font class、Symbol。选择 Font class 并生成在线代码并复制，之后找到主题文件 hexo-theme-kaze/layout/_partial/head.ejs 中 110 行左右的如下代码：
   <%# main css %&gt;   <%- css('css/main.css') %&gt;   <%# default icon %&gt;   <%- css('//at.alicdn.com/t/font_1946621_i1kgafibvw.css') %&gt;   <%# social icon %&gt;   <%- css('//at.alicdn.com/t/font_1952792_89b4ac4k4up.css') %&gt;
 
在 social icon 后一行添加自定义 icon 如
 <%- css('your generated links') %&gt;
 
即可使用自定义图标。
 
如果有其他问题或者需求可以继续跟进 issue。
