### ISSUE TITLE
category 二级目录问题

### ISSUE THREAD

**Issue by CCandle** [theme-kaze/hexo-theme-kaze#32]
我注意到category的hexo目录管理方式与kaze的访问方式有区别。
hexo中，
![image](https://user-images.githubusercontent.com/45314580/108150180-36a28200-710f-11eb-961d-7daaeac65d45.png)
这样的方式会被默认为img 是 test 的下级目录
但kaze会认为这是test的同级目录，在kaze中试图访问时会出现目录错误
![image](https://user-images.githubusercontent.com/45314580/108150269-6782b700-710f-11eb-9101-6d941bb0ca13.png)

**Comment by songhn233** [comment]
Hexo 文档中有提到这种多分类的特性。不过本主题并没有处理，目前仅支持单分类。

目前建议 categories 处理单分类，有多级需求用 tags 处理。

如果有多分类的需求我最近有空加一下。

**Comment by Phenothalin** [comment]
好的，辛苦了
我认为如果支持多级分类的话，主题的实用性能得到一定的提高




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "theme-kaze/hexo-theme-kaze"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 中午1:10
收件人:&nbsp;"theme-kaze/hexo-theme-kaze"<hexo-theme-kaze@noreply.github.com&gt;;
抄送:&nbsp;"CC&amp;&amp;le"<2987794676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [theme-kaze/hexo-theme-kaze] category 二级目录问题 (#32)





 
Hexo 文档中有提到这种多分类的特性。不过本主题并没有处理，目前仅支持单分类。
 
目前建议 categories 处理单分类，有多级需求用 tags 处理。
 
如果有多分类的需求我最近有空加一下。

**Comment by lujw666** [comment]
我的问题差不多，但问题相反
categories:
    - [test, img]
  做上下级分类时变成同级分类导致目录出错

**Comment by 0x4qE** [comment]
> 我注意到category的hexo目录管理方式与kaze的访问方式有区别。
> hexo中，
> ![image](https://user-images.githubusercontent.com/45314580/108150180-36a28200-710f-11eb-961d-7daaeac65d45.png)
> 这样的方式会被默认为img 是 test 的下级目录
> 但kaze会认为这是test的同级目录，在kaze中试图访问时会出现目录错误
> ![image](https://user-images.githubusercontent.com/45314580/108150269-6782b700-710f-11eb-9101-6d941bb0ca13.png)

请问是否用的是最新版的 hexo ？我也在本地尝试了一下，如果用最新版的 hexo`^5.4.0` ，没有出现目录的访问错误。如果想要用多级目录的话，可以用 `[test,img]` 的方式。

**Comment by 0x4qE** [comment]
> 我的问题差不多，但问题相反
> categories:
> - [test, img]
> 做上下级分类时变成同级分类导致目录出错

能否提供更多的信息（截图和描述）？是否用的是最新版的 `hexo` 以及 `hexo-theme-kaze` 的 `devel` 分支？

**Comment by lujw666** [comment]
> > 我的问题差不多，但问题相反
> > categories:
> > 
> > * [test, img]
> >   做上下级分类时变成同级分类导致目录出错
> 
> 能否提供更多的信息（截图和描述）？是否用的是最新版的 `hexo` 以及 `hexo-theme-kaze` 的 `devel` 分支？

使用`master`分支，已使用`<%- list_categories(site.categories) %> `解决

**Comment by songhn233** [comment]
@CCandle @lujw666 

之前应该已经在 `devel` 分支[修复](https://github.com/theme-kaze/hexo-theme-kaze/pull/35/commits/6ef342fb3d5dee1598aa143c959e9e57b62a6853)过链接错误的问题了，现在已经合并到 `master` 分支了

可以测试一下现在是否正常，我们顺便增强了多分支的显示，目前的问题是 Hexo 官方把子分类的所有父分类都考虑在了当前分类中，但是感觉违背直觉，所以首页文章子分类我们取消了父分类的显示，同时在分类页面增加了子分类的前缀

如果有其他关于分类的问题和建议欢迎提供
