### ISSUE TITLE
python代码块的显示问题

### ISSUE THREAD

**Issue by bubbleboy11** [theme-kaze/hexo-theme-kaze#36]
## hexo: 5.0.2 ，python代码块的显示有问题
左图是hexo渲染效果，右图是原始文本
python标记的代码块表示则大括号不显示，Python标记的代码块能显示大括号却没有高亮

![屏幕截图 2021-04-02 213739](https://user-images.githubusercontent.com/49860518/113420768-77730380-93fc-11eb-8b08-88cbc5c2fe68.jpeg)

**Comment by bubbleboy11** [comment]
原来是在hexo修改高亮而不是主题下修改，打扰了

**Comment by songhn233** [comment]
如果没有其他问题将关闭这个 issue
