### ISSUE TITLE
在hexo根目录下url加入了root目录设置后，会出现奇怪的现象 

### ISSUE THREAD

**Issue by henmawq** [theme-kaze/hexo-theme-kaze#37]
在根目录的config.yml中
url: https://mawei2019.gitee.io/
root: /new
这个设置在我用next主题就没有问题。

使用kaze主题 ，我不晓得在主题下的config.yml还需要怎么样的设置 
使用hexo s 启动服务后，网页将会不正确，无法访问。

**Comment by henmawq** [comment]
https://mawei2019.gitee.io/new    可以访问一下这个试试，点进去后，再点首页，会发现，网页根本没有取到子目录new

**Comment by songhn233** [comment]
现 [已适配](https://github.com/theme-kaze/hexo-theme-kaze/commit/25f13ffbc80d09560aa057cf4f06459c81dd4ef0) 二级目录，由于修改文件较多建议切换 [devel](https://github.com/theme-kaze/hexo-theme-kaze/tree/devel) 分支直接下载使用最新主题。

如果还有二级目录适配问题可以继续跟进该 issue。

**Comment by henmawq** [comment]
完美 ，哈哈，我以为是自己弄错了，测试一天。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月14日 0:17
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [theme-kaze/hexo-theme-kaze] 在hexo根目录下url加入了root目录设置后，会出现奇怪的现象 (#37)


现 已适配<https://github.com/theme-kaze/hexo-theme-kaze/commit/25f13ffbc80d09560aa057cf4f06459c81dd4ef0> 二级目录，由于修改文件较多建议切换 devel<https://github.com/theme-kaze/hexo-theme-kaze/tree/devel> 分支直接下载使用最新主题。

如果还有二级目录适配问题可以继续跟进该 issue。

―

**Comment by henmawq** [comment]
还有一个问题，开启搜索后不起作用。搜索不工作。devel分支。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月14日 0:17
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [theme-kaze/hexo-theme-kaze] 在hexo根目录下url加入了root目录设置后，会出现奇怪的现象 (#37)


现 已适配<https://github.com/theme-kaze/hexo-theme-kaze/commit/25f13ffbc80d09560aa057cf4f06459c81dd4ef0> 二级目录，由于修改文件较多建议切换 devel<https://github.com/theme-kaze/hexo-theme-kaze/tree/devel> 分支直接下载使用最新主题。

如果还有二级目录适配问题可以继续跟进该 issue。

―

**Comment by henmawq** [comment]
1、devel 分支里主题 下的config.yml开启搜索为true后，搜索不起作用
需要额外再安装什么插件吗
2、右下角的弹出菜单，其中，搜索 、黑白切换，都无效，有个目录的小按钮，如果在首页的状态 下，是变得更黑
3、第三个问题：下面的计算访客次数，访问量次，并不显示数字。在confiy.yml是开启状态。
4、每个文章最下方的文章链接不对，里面缺少了子目录。
