### ISSUE TITLE
主题多级目录适配相关问题

### ISSUE THREAD

**Issue by songhn233** [theme-kaze/hexo-theme-kaze#39]
1、devel 分支里主题 下的config.yml开启搜索为true后，搜索不起作用
需要额外再安装什么插件吗
2、右下角的弹出菜单，其中，搜索 、黑白切换，都无效，有个目录的小按钮，如果在首页的状态 下，是变得更黑
3、第三个问题：下面的计算访客次数，访问量次，并不显示数字。在confiy.yml是开启状态。
4、每个文章最下方的文章链接不对，里面缺少了子目录。

_Originally posted by @henmawq in https://github.com/theme-kaze/hexo-theme-kaze/issues/37#issuecomment-819532159_

**Comment by songhn233** [comment]
@henmawq
1. 由于 Hexo 的机制请确保在修改 config 后重新 `hexo clean & hexo g`。正确设置后会在 `public` 目录下生成 `search.json` 文件。之后目前的建议是直接在 `theme/source/js/main.js` 下最后的
```js
setTimeout(() => {
  localSearch('/search.json')
}, 0)
```
改为
```js
setTimeout(() => {
  localSearch('new/search.json')
}, 0)
```
2. 估计你是直接在 devtool 里打开手机视图？手机访问应该是不存在问题的。在不刷新的前提下直接从桌面切换到手机会出现你提到的问题，由于使用中并不会出现这样的情况，所以没有对当前屏幕尺寸变化做监听，在手机宽度下直接刷新即可。
3. 最好提供线上案例，并且访问次数统计由于依赖 busuanzi 所以在 localhost 模式下可能会出现一些显示问题。
4. 第四点和第一点中都是针对二级目录的问题，具体修改可能要到周末。

**Comment by henmawq** [comment]
改为

setTimeout(() => {
  localSearch('new/search.json')
}, 0)
试了，搜索仍然没有反应。search.json 文件内容中的连接也是缺少子目录的。

**Comment by songhn233** [comment]
> 改为
> 
> 
> 
> setTimeout(() => {
> 
>   localSearch('new/search.json')
> 
> }, 0)
> 
> 试了，搜索仍然没有反应。search.json 文件内容中的连接也是缺少子目录的。

首先确定2和3的问题是否解决。
1和4都是子目录相关问题，会在周末解决～

**Comment by henmawq** [comment]
> > 改为
> > setTimeout(() => {
> > localSearch('new/search.json')
> > }, 0)
> > 试了，搜索仍然没有反应。search.json 文件内容中的连接也是缺少子目录的。
> 
> 首先确定 2 和 3 的问题是否解决。
> 1 和 4 都是子目录相关问题，会在周末解决～

2没有问题， 3不论本地测试还是在线测试，不会显示 本站总访问量次 |本站总访客数次   中间不显示任何数字。

**Comment by songhn233** [comment]
> > > 改为
> > > setTimeout(() => {
> > > localSearch('new/search.json')
> > > }, 0)
> > > 试了，搜索仍然没有反应。search.json 文件内容中的连接也是缺少子目录的。
> > 
> > 
> > 首先确定 2 和 3 的问题是否解决。
> > 1 和 4 都是子目录相关问题，会在周末解决～
> 
> 2没有问题， 3不论本地测试还是在线测试，不会显示 本站总访问量次 |本站总访客数次 中间不显示任何数字。

3 有线上可复现 demo 吗，方便错误排查

**Comment by henmawq** [comment]
> > > > 改为
> > > > setTimeout(() => {
> > > > localSearch('new/search.json')
> > > > }, 0)
> > > > 试了，搜索仍然没有反应。search.json 文件内容中的连接也是缺少子目录的。
> > > 
> > > 
> > > 首先确定 2 和 3 的问题是否解决。
> > > 1 和 4 都是子目录相关问题，会在周末解决～
> > 
> > 
> > 2没有问题， 3不论本地测试还是在线测试，不会显示 本站总访问量次 |本站总访客数次 中间不显示任何数字。
> 
> 3 有线上可复现 demo 吗，方便错误排查

https://mawei2019.gitee.io/new/2021/04/13/hello-world/  这是线上，你看下文章，多少次，是不显示的

**Comment by songhn233** [comment]
这依然是二级目录造成的问题，完整的适配会在周末跟进 :zzz:

**Comment by henmawq** [comment]
> 这依然是二级目录造成的问题，完整的适配会在周末跟进 💤

适配过了吗

**Comment by henmawq** [comment]
> 这依然是二级目录造成的问题，完整的适配会在周末跟进 💤

setTimeout(() => {
localSearch('/new/search.json')
}, 0)
new前加了一个 / 居然可以搜索 了，但是搜索出的连接是不对的。连接中没有子目录，也就是json里的内容不对。

**Comment by songhn233** [comment]
> > 这依然是二级目录造成的问题，完整的适配会在周末跟进 💤
> 
> setTimeout(() => {
> localSearch('/new/search.json')
> }, 0)
> new前加了一个 / 居然本地可以搜索 了，在线却不行，但是搜索出的连接是不对的。连接中没有子目录，也就是json里的内容不对。

已在 f427507 尝试增强多级目录功能。

多级目录对于搜索需要做如下设置：

找到 `theme/config.yml` 下的

```yaml
search:
  enable: false
  path: search.json
  field: posts
  searchContent: true
```
修改为
```yaml
search:
  enable: true
  path: /second/search.json # 这里填写需要的多级目录，比如你应该填写 /new/search.json
  field: posts
  searchContent: true
```
其他诸如画廊、访问统计等插件在文章页的问题均已修复。

可以下载最新 `devel` 分支测试，如有问题可以继续跟进。

**Comment by henmawq** [comment]
还有问题，
第一、每个文章下方 的

作者：ma
文章链接：https://mawei2019.gitee.io/about/index.html
版权声明：本博客所有文章除特别声明外，均采用CC BY-NC-SA 4.0 协议。转载请注明出处！

文章链接是不对的。少了子目录。

第二、在手机真实环境下，显示的图片很奇怪，图片之间的间隔非常大。
https://mawei2019.gitee.io/new/2021/04/05/v2rayn/
可以用手机访问测试一下。

**Comment by songhn233** [comment]
> 还有问题，
> 
> 第一、每个文章下方 的
> 
> 
> 
> 作者：ma
> 
> 文章链接：https://mawei2019.gitee.io/about/index.html
> 
> 版权声明：本博客所有文章除特别声明外，均采用CC BY-NC-SA 4.0 协议。转载请注明出处！
> 
> 
> 
> 文章链接是不对的。少了子目录。
> 
> 
> 
> 第二、在手机真实环境下，显示的图片很奇怪，图片之间的间隔非常大。
> 
> https://mawei2019.gitee.io/new/2021/04/05/v2rayn/
> 
> 可以用手机访问测试一下。
> 
> 
> 
> 第三、kaze能否增加一个副标题的功能。让手机的情况下，能一眼看到网站的简单介绍，而不是只是一堆标签菜单。

具体描述一下副标题的特性？

**Comment by Dicemy** [comment]
请问一下当文章过长时右侧的文章目录显示不正常的问题如何解决啊？
>这是有问题的页面[http://dicemy.com/58095.html](http://dicemy.com/58095.html)

之前比较长的文章就出现过这种问题，有的时候不止是目录会出现排版错误，正文也会出现

**Comment by songhn233** [comment]
@Dicemy 方便提供一下 markdown 源文件吗

大概率是因为格式问题，不同编辑器处理 md 上有一些差别，有可能你本地编辑器正常 Hexo 解析出了问题。
