### ISSUE TITLE
搜索功能searchContent设为false后，就不显示搜索结果

### ISSUE THREAD

**Issue by abbw** [theme-kaze/hexo-theme-kaze#44]
搜索配置项的 `searchContent` 不是设为 `false` 后就只搜索文章标题吗？

如果是的话，那是一个bug了。

发现是 `main,js` 里的 `if (dataContent !== '') {` 这个判断导致不能搜索标题的，我尝试把它删除就行了

否则的话必须 `searchContent` 设为 `true` 才能有搜索结果

**Comment by songhn233** [comment]
[Fixed](https://github.com/theme-kaze/hexo-theme-kaze/commit/ab3a35c9f0622b43ef200b2464b75e08133d74fa)

**Comment by abbw** [comment]
> 
> 
> [Fixed](https://github.com/theme-kaze/hexo-theme-kaze/commit/ab3a35c9f0622b43ef200b2464b75e08133d74fa)

我试了下直接替换 `main.js` 的所有内容，并没效果，而且问题更大了。

无论输入什么搜索内容，都会显示出所有文章，哪怕关键词不存在。

我站点已经另寻僻径解决了，不过还是希望未来能fix，不然不好合并。

感谢作者~

**Comment by songhn233** [comment]
> > [Fixed](https://github.com/theme-kaze/hexo-theme-kaze/commit/ab3a35c9f0622b43ef200b2464b75e08133d74fa)
> 
> 我试了下直接替换 `main.js` 的所有内容，并没效果，而且问题更大了。
> 
> 无论输入什么搜索内容，都会显示出所有文章，哪怕关键词不存在。
> 
> 我站点已经另寻僻径解决了，不过还是希望未来能fix，不然不好合并。
> 
> 感谢作者~

后续会处理这个问题的，最近有点忙。

另外设置 searchContent 是出于怎样的目的？是否是因为 data.json 文件过大。

那么 algolia 这样的搜索服务不知是否有需求？

**Comment by abbw** [comment]
> 
> 
> > > [Fixed](https://github.com/theme-kaze/hexo-theme-kaze/commit/ab3a35c9f0622b43ef200b2464b75e08133d74fa)
> > 
> > 
> > 我试了下直接替换 `main.js` 的所有内容，并没效果，而且问题更大了。
> > 无论输入什么搜索内容，都会显示出所有文章，哪怕关键词不存在。
> > 我站点已经另寻僻径解决了，不过还是希望未来能fix，不然不好合并。
> > 感谢作者~
> 
> 后续会处理这个问题的，最近有点忙。
> 
> 另外设置 searchContent 是出于怎样的目的？是否是因为 data.json 文件过大。
> 
> 那么 algolia 这样的搜索服务不知是否有需求？

algolia 我用上了，不过又舍弃了。

searchContent 是因为个人觉得内容重复，达不到搜索需要，使用标题比较准确
