### ISSUE TITLE
能让文章内容部分比例在大一点吗

### ISSUE THREAD

**Issue by SunIsComing** [theme-kaze/hexo-theme-kaze#45]
很喜欢这个主题，内容也很丰富，但我不太喜欢这个布局，博文内容的比例能提高一点吗，这样好提升阅读博客的沉浸体验感

**Comment by songhn233** [comment]
感谢反馈，内容比例是指现在手机布局下每行显示内容过窄吗？

如果是这个问题最近可以调整手机布局为窄边框或者可能直接把边框取消。

**Comment by SunIsComing** [comment]
![image](https://user-images.githubusercontent.com/37065209/121130823-87c2b700-c861-11eb-9030-15491b533436.png)
pc上的布局，希望中间文章部分能在大一点，那个可以怎么调吗

**Comment by songhn233** [comment]
如果想修改页面宽度的话，可以找到 `themes/hexo-theme-kaze/source/css/_pages/widgets/columns.styl` 文件：
```css
@media screen and (min-width: 1280px)
  .left-column .display-when-two-columns, .widescreen-archive
    display: none
  .main-column
    width: 52%
  .left-column, .right-column
    width: 24%
  .right-column
    order: 3
    display: block
```
修改 `main-column` 比例之后重新 `hexo clean & hexo g` 即可，同时注意宽度相加要为 100% 即可，其他布局也可以类似修改

**Comment by songhn233** [comment]
还有其他问题吗

**Comment by songhn233** [comment]
issue 先关闭了，如果还有问题再开新的好了
