### ISSUE TITLE
脚注添加

### ISSUE THREAD

**Issue by eoinli** [theme-kaze/hexo-theme-kaze#52]
**Is your feature request related to a problem? Please describe. 你的特性请求是因为什么问题？**
写文章需要添加参考信息时，markdown 中的脚注（`[^1]`之类）在应用主题时没有生效。

**Describe the solution you'd like 描述新特性的需求**
希望可以添加脚注的适配，即文章中可以通过`[^]`定义脚注，鼠标悬停在脚注上可以预览脚注内容，点击脚注后可以跳转到文章底部的脚注部分；而每一条脚注还有一个返回原文位置的链接，类似于维基百科的脚注。

![image](https://user-images.githubusercontent.com/88650074/131178491-a4c38cd1-5013-408e-90ab-bac6d0a2ad51.png)
![image](https://user-images.githubusercontent.com/88650074/131178521-534c618c-f3e2-4fb3-8952-c2512ef663df.png)
![image](https://user-images.githubusercontent.com/88650074/131178572-63064e4a-6087-4096-ab20-8c7ea0a2ecc3.png)

**Comment by songhn233** [comment]
这是由于 Hexo 默认的渲染器不支持该特性，可以通过替换为 [hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus) 来支持该特性。

同时主题也对 katex 进行了适配，如果有公式渲染需求使用该渲染器也是一个更好的选择，可以查看主题 [公式渲染文档](https://demo.theme-kaze.top/latex/)。

```
npm uninstall hexo-renderer-marked -S
npm install hexo-renderer-markdown-it-plus -S
```
之后即可使用 footnote 功能，更多支持的 markdown 语法可以参考对应渲染器文档。

**Comment by eoinli** [comment]
感谢！

**Comment by eoinli** [comment]
感谢！
