### ISSUE TITLE
我该如何添加 自定义的图标

### ISSUE THREAD

**Issue by Uranus-s** [theme-kaze/hexo-theme-kaze#54]
**Describe the bug 描述问题**
A clear and concise description of what the bug is. 简要描述所遇到的问题

**To Reproduce 如何复现**
Steps to reproduce the behavior. 简要描述复现步骤或提供最小可复现 demo

**Environment 使用环境**
 - Hexo Version 使用 Hexo 版本
 - Theme Version 使用主题版本
 - Browser 浏览器版本（可选）

**Additional context 额外信息**
Add any other context about the problem here. 额外需要说明的内容

**Comment by songhn233** [comment]
可以参考 [相关 issue](https://github.com/theme-kaze/hexo-theme-kaze/issues/31#issuecomment-779822037)，简单来说是在 iconfont 中选择需要的 icon 再生成 css 后插入到主题模板中。

**Comment by songhn233** [comment]
如果没有其他问题将关闭这个 issue。
