### ISSUE TITLE
图片无法显示或无法get

### ISSUE THREAD

**Issue by chengyangliu47** [theme-kaze/hexo-theme-kaze#58]
**Describe the bug 描述问题**
我插入的图片不显示，但是有实体可以点开，于是我建了个新的hexo测试，图片显示无异常和获取，然后改kaze-theme以后图片能正常显示但是点开是"Cannot GET /2022/01/13/test/null". 文件夹结构均为

source
     -test.md
      test
          abc.jpg

两次场景图片插入方式均为{% asset_img abc.jpg url_vs_uri %}, hexo的config.yml已经修改为post_asset_folder: true
                

**To Reproduce 如何复现**
安装hexo和kaze后新建post后插入图片即可

**Environment 使用环境**
 - Hexo Version 使用 Hexo 版本
 - Theme Version 使用主题版本
 
hexo: 6.0.0
hexo-cli: 4.3.0
os: win32 10.0.22000
node: 16.13.1
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

 - Browser 浏览器版本（可选）
96.0.4664.110

**Additional context 额外信息**
图片显示空白的kaze项目和对照组kaze仅改了背景色主题和post_asset_folder: true，纯对照组hexo没有任何修改，图片获取显示均正常。

**Comment by songhn233** [comment]
> **Describe the bug 描述问题** 我插入的图片不显示，但是有实体可以点开，于是我建了个新的hexo测试，图片显示无异常和获取，然后改kaze-theme以后图片能正常显示但是点开是"Cannot GET /2022/01/13/test/null". 文件夹结构均为
> 
> source -test.md test abc.jpg

我这里复现的结果是点击可以正常预览图片，但是在文章中无法显示。初步判断是 asset_img 的一些机制导致 lazyload 失败了。

建议是可以先回避使用这个特性，其他方式都可以做到类似的效果。而且这个特性依赖标签插件，实际上如果后面要迁移 markdown 文件的话这种依赖特定主题 / 引擎的扩展总归是有迁移成本的，尤其是放在图片这样基本的需求上。

可以直接在 source 中用 img folder 管理图片，也可以嵌套文件夹来实现类似的管理分类效果。

或者使用自建图床，之后用 url 方式引用图片。

**Comment by chengyangliu47** [comment]
> > **Describe the bug 描述问题** 我插入的图片不显示，但是有实体可以点开，于是我建了个新的hexo测试，图片显示无异常和获取，然后改kaze-theme以后图片能正常显示但是点开是"Cannot GET /2022/01/13/test/null". 文件夹结构均为
> > source -test.md test abc.jpg
> 
> 我这里复现的结果是点击可以正常预览图片，但是在文章中无法显示。初步判断是 asset_img 的一些机制导致 lazyload 失败了。
> 
> 建议是可以先回避使用这个特性，其他方式都可以做到类似的效果。而且这个特性依赖标签插件，实际上如果后面要迁移 markdown 文件的话这种依赖特定主题 / 引擎的扩展总归是有迁移成本的，尤其是放在图片这样基本的需求上。
> 
> 可以直接在 source 中用 img folder 管理图片，也可以嵌套文件夹来实现类似的管理分类效果。
> 
> 或者使用自建图床，之后用 url 方式引用图片。

感谢解答！想细问一下
> 可以直接在 source 中用 img folder 管理图片，也可以嵌套文件夹来实现类似的管理分类效果。
是指用相对路径或者绝对路径插入图片吗，我用相对路径不知道为什么图片显示不出来，如果不行估计只能用图床了。抱歉我比较萌新问了这么多。

**Comment by songhn233** [comment]
> 是指用相对路径或者绝对路径插入图片吗，我用相对路径不知道为什么图片显示不出来，如果不行估计只能用图床了。抱歉我比较萌新问了这么多。

可以保持这样的结构
```
- source
-- img
--- test.jpg
-- _posts
--- test.md
```

之后需要在 markdown 中引用的话可以直接 `![test](/img/test.jpg)`

**Comment by chengyangliu47** [comment]
> > 是指用相对路径或者绝对路径插入图片吗，我用相对路径不知道为什么图片显示不出来，如果不行估计只能用图床了。抱歉我比较萌新问了这么多。
> 
> 可以保持这样的结构
> 
> ```
> - source
> -- img
> --- test.jpg
> -- _posts
> --- test.md
> ```
> 
> 之后需要在 markdown 中引用的话可以直接 `![test](/img/test.jpg)`

非常感谢！

**Comment by chengyangliu47** [comment]
> > 是指用相对路径或者绝对路径插入图片吗，我用相对路径不知道为什么图片显示不出来，如果不行估计只能用图床了。抱歉我比较萌新问了这么多。
> 
> 可以保持这样的结构
> 
> ```
> - source
> -- img
> --- test.jpg
> -- _posts
> --- test.md
> ```
> 
> 之后需要在 markdown 中引用的话可以直接 `![test](/img/test.jpg)`

抱歉我第一次回答好像写错了，我的文件夹结果就是你说的这样，但是图片既无法预览也无法显示，
-_post
--test.md
--test
---abc.jpg
然后用
```
![](/test/abc.jpg)
```
就是这样test.md文件和test文件夹平级，引用的时候无法显示也无法预览

**Comment by songhn233** [comment]
> 就是这样test.md文件和test文件夹平级，引用的时候无法显示也无法预览

平级的结构不经过处理是无法正常解析的。你列出的这个结构和我给的是不一样的，img folder 实际上应该作为 source 的子目录，然后其他 markdown 通过绝对路径加载。

原理的话可以简单理解为 source 下额外的文件（在这里是 img）会被直接拷贝到最后站点的静态资源中，这样用绝对路径的话实际上是通过 url 访问站点的静态资源，而不是从本地文件的结构去考虑的。

**Comment by chengyangliu47** [comment]
> > 就是这样test.md文件和test文件夹平级，引用的时候无法显示也无法预览
> 
> 平级的结构不经过处理是无法正常解析的。你列出的这个结构和我给的是不一样的，img folder 实际上应该作为 source 的子目录，然后其他 markdown 通过绝对路径加载。
> 
> 原理的话可以简单理解为 source 下额外的文件（在这里是 img）会被直接拷贝到最后站点的静态资源中，这样用绝对路径的话实际上是通过 url 访问站点的静态资源，而不是从本地文件的结构去考虑的。

问题解决啦！万分感谢，我还是太才疏学浅了！
