### ISSUE TITLE
一级标题字体过小

### ISSUE THREAD

**Issue by Ch3nYe** [theme-kaze/hexo-theme-kaze#60]
**Describe the bug 描述问题**
h1 title is too small, 一级标题字体过小.
不知道开发者处于什么目的将h1设置的非常小，可能有某些特别的考虑，但是对于我来说需要h1字体要大一些，因为我所有的文章中标题都是从#开始的.

**Environment 使用环境**
 - Hexo Version hexo: 5.3.0
 - Theme Version 1.1.0-beta5

**Solution 解决方法**
修改了kaze/source/css/_base/reset.styl
将line4: h1, h2, h3, h4, h5, h6 中的h1单独拿出来定义：
```
h1 
  font-size: 200%
  font-weight: 700
  line-height: 1.25
  color: var(--title-color)
h2, h3, h4, h5, h6
  font-size: 100%
  font-weight: 700
  line-height: 1.25
  color: var(--title-color)
```

**Comment by Ch3nYe** [comment]
如上所示，已经解决.

**Comment by songhn233** [comment]
可以参考 #53 的回答，可以认为是通过异常的行为来保证书写的最佳实践

这个解决方案会在 issue 中 pin
