### ISSUE TITLE
主题配置

### ISSUE THREAD

**Issue by skillfans** [theme-kaze/hexo-theme-kaze#62]
作者你好，想咨询一下，主题内置的社交链接图标在哪个配置文件里呢？

**Comment by songhn233** [comment]
> 作者你好，想咨询一下，主题内置的社交链接图标在哪个配置文件里呢？

在 [文档中](https://demo.theme-kaze.top/document/#%E5%9B%BE%E6%A0%87) 有记录

![image](https://user-images.githubusercontent.com/47357585/162783325-de2b924a-1a54-4234-ace1-a952ddfed0fa.png)

对于自定义图标的需求可以采用自建 iconfont 素材库的方式，可以参考 https://github.com/theme-kaze/hexo-theme-kaze/issues/31#issuecomment-779822037
