### ISSUE TITLE
categories页面显示有误

### ISSUE THREAD

**Issue by CCandle** [theme-kaze/hexo-theme-kaze#63]
hexo: 6.1.0
kaze: ^1.0.5
我现在有一个分类为 'C/C++'，这在[post页面](https://ccandle.top/C-C/2019-c/)和次级[categories页面](https://ccandle.top/categories/C-C/)都能正常显示，然而在[categories页面](https://ccandle.top/categories/)则显示为 'C-C'。
据我观察似乎跟public文件夹中生成的目录名为 'C-C' 有一定的关系，但是其他页面又能够正常显示，请问这可以修复么

**Comment by CCandle** [comment]
我似乎明白了，也就是说出问题的页面是因为hexo解析出问题，只能等hexo官方修复了。那我就更改分类名称避免这个问题吧。

**Comment by songhn233** [comment]
> 我似乎明白了，也就是说出问题的页面是因为hexo解析出问题，只能等hexo官方修复了。那我就更改分类名称避免这个问题吧。

~~这个应该不用等，看 issue 应该不准备修~~

通过 `category_map` 映射应该也能解决这个问题，或者可以用 `CPP` 这种说法，看你选择

**Comment by CCandle** [comment]
> > 我似乎明白了，也就是说出问题的页面是因为hexo解析出问题，只能等hexo官方修复了。那我就更改分类名称避免这个问题吧。
> 
> ~这个应该不用等~，看 issue 应该不准备修
> 
> 通过 `category_map` 映射应该也能解决这个问题，或者可以用 `CPP` 这种说法，看你选择

抱歉，我想指出更改 `category_map` 并不能解决这个问题。我发现，对于 `C++: cpp` 来说，在文章中显示的 `C++` ，而在category页面显示的是 `cpp`，就像这样：

![目录页](https://user-images.githubusercontent.com/45314580/164580010-4a3efdf3-bb45-4307-8a05-1bc1c229d8e7.png)

![次级目录页](https://user-images.githubusercontent.com/45314580/164580249-e4d860a8-3953-4b70-9e67-c5e41ed82862.png)

![文章详情页](https://user-images.githubusercontent.com/45314580/164580315-6943d1c6-88f2-4dc8-9104-cbed21bcf6e4.png)

**Comment by songhn233** [comment]
> > > 我似乎明白了，也就是说出问题的页面是因为hexo解析出问题，只能等hexo官方修复了。那我就更改分类名称避免这个问题吧。
> > 
> > 
> > ~这个应该不用等~，看 issue 应该不准备修
> > 通过 `category_map` 映射应该也能解决这个问题，或者可以用 `CPP` 这种说法，看你选择
> 
> 抱歉，我想指出更改 `category_map` 并不能解决这个问题。我发现，对于 `C++: cpp` 来说，在文章中显示的 `C++` ，而在category页面显示的是 `cpp`，就像这样：
> 
> ![目录页](https://user-images.githubusercontent.com/45314580/164580010-4a3efdf3-bb45-4307-8a05-1bc1c229d8e7.png)
> 
> ![次级目录页](https://user-images.githubusercontent.com/45314580/164580249-e4d860a8-3953-4b70-9e67-c5e41ed82862.png)
> 
> ![文章详情页](https://user-images.githubusercontent.com/45314580/164580315-6943d1c6-88f2-4dc8-9104-cbed21bcf6e4.png)

好吧，那还是考虑命名规避一下～
