### ISSUE TITLE
顶部导航栏设置相关问题

### ISSUE THREAD

**Issue by skillfans** [theme-kaze/hexo-theme-kaze#65]
作者您好，请问如果需要将顶部导航栏设置为靠右边展示，应该更改那个配置文件呢？
![image](https://user-images.githubusercontent.com/78021710/165226886-aab6e4ee-b26f-4f2c-9caf-0e88e9d44536.png)

**Comment by songhn233** [comment]
Hello，主题本身配置没有支持这种样式，但可以自定义样式解决，首先找到主题对应文件 `source/css/_pages/widgets/nav.styl`
https://github.com/theme-kaze/hexo-theme-kaze/blob/6d550acfc7945e54446f8c493e9217cab2597baf/source/css/_pages/widgets/nav.styl#L23-L26

增加两行样式

```diff
 .navbar-menu 
   font-size: $md-font-size 
   display: flex 
   align-items: center
+  margin-left: auto
+  margin-right: 20px
```

重新 `hexo g` 即可，效果参考：

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/47357585/166318054-9f3f3ecf-9b83-409f-bcce-7d629e3c1d4c.png">
