### ISSUE TITLE
字体更改

### ISSUE THREAD

**Issue by HobbitQia** [theme-kaze/hexo-theme-kaze#67]
请问可以使用多种字体吗？中文和英文分别用不同的字体是可以的吗？

**Comment by songhn233** [comment]
@HobbitQia hello，首先预设字体可以在 [font-family 字段](https://github.com/theme-kaze/hexo-theme-kaze/blob/master/_config.yml#L236) 里改。

至于这个需求其实是个 css 问题。中英对应不同的字体这个可以设置 font-family 的顺序，文字会匹配字体，如果当前字体中没有对应的文字会尝试匹配后一个字体直到最后的兜底字体（比如 sans），比如英文使用 [roboto](https://fonts.google.com/specimen/Roboto?query=robo) 而中文使用 [Noto Serif Simplified Chinese](https://fonts.google.com/noto/specimen/Noto+Serif+SC)，顺序书写即可
