### ISSUE TITLE
请问头像的背景是白色如何解决？

### ISSUE THREAD

**Issue by HobbitQia** [theme-kaze/hexo-theme-kaze#68]
如题，我的头像背景是白色的，导致在使用黑夜主题时会比较突兀，想问是否能使用圆形头像？或者有其他方法解决
![image](https://user-images.githubusercontent.com/89443407/170824774-08f980d1-7cb9-4dac-b9f6-a8a5362908a4.png)

**Comment by songhn233** [comment]
Hello，这个感觉可以抠图解决啊 😂

可以试试常见的去底色工具，黑边外边设置为透明色应该就行
