### ISSUE TITLE
关于可否添加一个编辑原文的功能

### ISSUE THREAD

**Issue by shuangxunian** [theme-kaze/hexo-theme-kaze#77]
![image](https://user-images.githubusercontent.com/45627134/203733333-21619453-7b2e-436e-8069-0e7d8b294d70.png)

这个编辑原文的功能我这里已经开发完了，不知道是否需要，如果需要我直接提pr合并进来~

**Comment by 0x4qE** [comment]
你好~这个需求可能是比较偏个性化的。`hexo` 本身是静态博客，没有「后台编辑」这样的元素，因此这样的更新可能适用性不是很强。当然如果有其他用户也有这样的需求的话，可以参考一下你的做法。

**Comment by songhn233** [comment]
> 这个编辑原文的功能我这里已经开发完了，不知道是否需要，如果需要我直接提pr合并进来~

Hello，看了下你的例子应该是基于 git hash 做的，可以 pr 一下

配置项可以简单做个开关，后面我们再看怎么做一些个性化配置

感谢～

**Comment by shuangxunian** [comment]
> 

那应该推到哪个分支方便咱们这边测试呢~

**Comment by songhn233** [comment]
> 那应该推到哪个分支方便咱们这边测试呢~

dev

**Comment by songhn233** [comment]
Close by https://github.com/theme-kaze/hexo-theme-kaze/pull/78.
