### ISSUE TITLE
请问如何修改滚动条宽度？

### ISSUE THREAD

**Issue by TURLEing** [theme-kaze/hexo-theme-kaze#80]
如下图，我想修改全局的滚动条样式，将其宽度调大一些，请问具体可以如何修改呢？

![image.png](https://s2.loli.net/2023/02/07/LENT5px4AH876d9.png)

**Comment by katorly** [comment]
只需要找到 `/themes/kaze/source/css/_base/reset.styl`，在该文件中找到
```css
::-webkit-scrollbar
  background-color: transparent
  width: 2px
  height: 3px
  background-clip: padding-box
```
把 `width: 2px` 中的数字改成您想要的宽度即可。  
_注意这会改动整个博客的所有滚动条宽度。_
